=== TrellixVulnTeam/Meerkat_QVGB/meerkat/elasticsearch/config/load_index_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Input schema for meerkat.elasticsearch.load_index_from_file",
	"description": "Input schema for meerkat.elasticsearch.load_index_from_file",
	"type": "object",
	"properties": {
		"batch_size": { "type": "integer", "minimum": 10},
		"concurrency": { "type": "integer", "minimum" : 1},
		"elasticsearch": { "$ref": "#/definitions/elasticsearch"},
		"input": { "$ref": "#/definitions/input"},
		"logging": { "$ref": "#/definitions/logging"}
	},
	"required" : ["batch_size", "concurrency", "elasticsearch", "input", "logging"],
	"definitions": {
		"elasticsearch": {
			"properties": {
				"boost_labels": {
					"type": "array",
					"minItems": 1,
					"items": { "type": "string" }
				},
				"boost_vectors": { "type": "object" },
				"cluster_nodes" : {
					"type": "array",
					"minItems": 1,
					"items": { "type": "string"},
					"uniqueItems": true
				},
				"comment": { "type": "object" },
				"composite_fields": {
					"type": "array",
					"items": { "type": "object"}
				},
				"dispersed_fields": {
					"type": "array",
					"items": { "type": "object"}
				},
				"index": {"type": "string"},
				"type": {"type": "string"},
				"type_mapping": {
					"type": "object",
					"properties": {
						"mappings": {"type": "object"},
						"settings": {
							"type": "object",
							"properties": {
								"number_of_replicas": {
									"type": "integer",
									"minimum": 0
								},
								"number_of_shards": {
									"type": "integer",
									"minimum": 1
								}
							},
							"required": ["number_of_replicas", "number_of_shards"]
						}
					},
					"required" : ["mappings", "settings"]
				}
			},
			"required" : ["boost_labels", "boost_vectors", "cluster_nodes", "index", "type"]
		},
		"input": {
			"properties": {
				"encoding" : { "enum": ["utf-8"] },
				"filename" : { "type": "string" }
			},
			"required": ["encoding", "filename"]
		},
		"logging": {
			"properties": {
				"console": { "enum": [true, false] },
				"formatter": { "type": "string" },
				"level": { "enum": ["debug", "info", "warning", "critical", "error"] },
				"path": { "type": "string" }
			},
			"required": ["console", "formatter", "level", "path"]
		}
	}
}

=== TrellixVulnTeam/Meerkat_QVGB/meerkat/elasticsearch/config/factual_loader.json
{
	"concurrency" : 8,
	"batch_size" : 500,
	"input" : {
		"filename" : "us_places.factual.v3_40.1460184797.tab",
		"encoding" : "utf-8"
	},
	"logging" : {
		"level" : "info",
		"path" : "out.log",
		"formatter" : "%(asctime)s - %(name)s - %(levelname)s - %(message)s",
		"console" : false
	},
	"elasticsearch" : {
		"cluster_nodes" : [
			"search-keyvalue-pcq5ynjmu6erk2logbfkwbwfo4.us-west-2.es.amazonaws.com:80"
        ],
		"index" : "factual_index",
		"type" : "factual_type",
		"boost_labels" : [ "query_string" ],
		"boost_vectors" : {
			"factual_id" :        [ 0.0 ],
			"name" :              [ 1.0 ],
			"detail":             [ 0.0 ]
		},
		"composite_fields" : [
			{
				"address" : {
					"components" : [ "address", "address_extended", "locality", "region",
						"postcode", "country" ],
					"format" : "{0} {1} {2}, {3} {4}, {5}",
					"index" : "not_analyzed",
					"type" : "string"
				}
			}
		],
		"dispersed_fields" : [
			{
				"address": {
					"dispersion_regex" : "^(?P<number_part>\\w+)\\s+(?P<street_part>.+)$",
					"components" : [
						{
							"name" : "number_part",
							"index" : "not_analyzed",
							"type" : "string"
						},
						{
							"name" : "street_part",
							"index" : "not_analyzed",
							"type" : "string"
						}
					]
				}
			}
		],
		"type_mapping" : {
			"mappings" : {
				"factual_type" : {
					"_source" : {
						"enabled" : true
					},
					"properties" : {
						"factual_id" : { "index" : "not_analyzed", "type" : "string" },
						"name" : { "index" : "analyzed", "type" : "string" },
						"detail" : { "index" : "not_analyzed", "type" : "string" }
					}
				}
			},
			"settings" : {
				"number_of_replicas" : 0,
				"number_of_shards" : 10
			}
		},
		"comment" : {
			"_routing" : {
				"required" : false,
				"path" : "region"
			}
		}
	}
}
