=== TrellixVulnTeam/Meerkat_QVGB/meerkat/web_service/schema_output_datadeal.json
{
	"$schema" : "http://json-schema.org/draft-04/schema#",
	"title" : "meerkat_categorize output",
	"description": "A schema for defining output from 'meerkat_categorize'",
	"type" : "object",
	"properties" : {
		"cobrand_id" : {
			"description" : "Yodlee's number to uniquely identify the cobrand",
			"type" : "number"
		},
		"user_id" : {
			"description" : "Yodlee's number to uniquely identify a user within a cobrand",
			"type" : "number"
		},
		"container" : { "enum" : [ "bank", "card" ] },
		"transaction_list" : {
			"description" : "An array containing at least one of the following response types.",
			"type" : "array",
			"minItems": 1,
			"uniqueItems": true
		}
	},
	"required": ["cobrand_id", "user_id", "container", "transaction_list"]
}

=== TrellixVulnTeam/Meerkat_QVGB/meerkat/web_service/example_output.json
{
	"cobrand_id" : 1234,
	"user_id" : 2345,
	"container" : "card",
	"transaction_list" : [
		{
			"transaction_id" : 1,
			"is_physical_merchant" : true,
			"match_found" : true,
			"merchant_name" : "Safeway",
			"store_id" : "#12",
			"category_labels" : ["Grocery", "Pharmacy"],
			"source" : "FACTUAL",
			"source_merchant_id" : "3ec075f0-33c2-11e4-8c21-0800200c9a66",
			"street" : "742 El Camino Real",
			"city" : "Sunnyvale",
			"state" : "CA",
			"country" : "US",
			"postal_code" : "94087",
			"website" : "",
			"phone_number" : "",
			"fax_number" : "",
			"chain_name" : "",
			"neighborhood" : "",
			"transaction_origin" : ""
		},
		{
			"transaction_id" : 2,
			"is_physical_merchant" : false,
			"txn_type" : "Payment",
			"txn_sub_type": "",
			"category_labels" : [""],
			"website" : "",
			"phone_number" : "",
			"fax_number" : "",
			"chain_name" : "",
			"neighborhood" : "",
			"transaction_origin" : ""
		},
		{
			"transaction_id" : 3,
			"is_physical_merchant" : false,
			"merchant_name" : "Amazon",
			"website" : "",
			"phone_number" : "",
			"fax_number" : "",
			"chain_name" : "",
			"neighborhood" : "",
			"transaction_origin" : "",
			"category_labels" : ["General Merchandise"]
		},
		{
			"transaction_id" : 4,
			"is_physical_merchant" : true,
			"website" : "",
			"phone_number" : "",
			"fax_number" : "",
			"chain_name" : "",
			"neighborhood" : "",
			"transaction_origin" : "",
			"match_found" : false
		},
		{
			"transaction_id" : 5,
			"is_physical_merchant" : false,
			"website" : "",
			"phone_number" : "",
			"fax_number" : "",
			"chain_name" : "",
			"neighborhood" : "",
			"transaction_origin" : "",
			"match_found" : false
		}
	]
}

=== TrellixVulnTeam/Meerkat_QVGB/Meerkat/data/input/small_input.json
{
  "cobrand_id" : 1234,
  "user_id" : 2345,
  "container" : "bank",
  "transaction_list" : [
  {
    "amount":11.88,
    "date":"2014-12-22",
    "ledger_entry":"debit",
    "description":"DEBIT CARD PURCHASE   XXXXX0355     MCDONALDS F3441          CORBIN      KY",
    "transaction_id":1
  },
  {
    "amount":45.42,
    "date":"2014-12-01",
    "ledger_entry":"debit",
    "description":"FRED MEYER               ANCHORAGE    AK~~08888~~5438058079334354~~94022~~0~~~~0066",
    "transaction_id":2
  },
  {
    "amount":4.99,
    "date":"2014-12-09",
    "ledger_entry":"debit",
    "description":"CHECKCARD  1208 APL* ITUNES.COM/BILL                        866-712-7753 CA 24692164342000869308530",
    "transaction_id":3
  }]
}

=== TrellixVulnTeam/Meerkat_QVGB/meerkat/web_service/example_output_datadeal.json
{
	"cobrand_id" : 1234,
	"user_id" : 2345,
	"container" : "card",
	"transaction_list" : [
            {
                "address": "4316 Buffalo Rd",
                "city": "Erie",
                "latitude": "42.1461353",
                "longitude": "-80.0045373",
                "merchant_name": "McDonald's",
                "phone": "(814) 899-1000",
                "row_id": 45431,
                "state": "PA",
                "store_number": "3423",
                "website_url": "www.mcdonalds.com",
                "zip_code": "16510"
            },
            {
                "address": "6200 Chew Ave",
                "city": "Philadelphia",
                "latitude": "40.0496001",
                "longitude": "-75.1719993",
                "merchant_name": "U-Haul",
                "phone": "(215) 844-1690",
                "row_id": 76554,
                "state": "PA",
                "store_number": "43754",
                "website_url": "www.uhaul.com/",
                "zip_code": "19138"
            },
            {
                "address": "1089 Central St",
                "city": "Leominster",
                "latitude": "42.4975025",
                "longitude": "-71.7455895",
                "merchant_name": "Dollar Tree",
                "phone": "(978) 534-7283",
                "row_id": 71755,
                "state": "MA",
                "store_number": "4474",
                "website_url": "www.dollartree.com",
                "zip_code": "01453-4807"
            }
	]
}

=== TrellixVulnTeam/Meerkat_QVGB/web_service_tester/new_york.json
{
    "cobrand_id": 2,
    "container": "bank",
    "transaction_list": [
        {
            "amount": 19.99,
            "date": "2014-08-10T00:00:00",
            "description": "McDonald's Hamburgers New York, NY",
            "ledger_entry": "debit",
            "transaction_id": 1
        },
        {
            "amount": 29.99,
            "date": "2014-08-10T00:00:00",
            "description": "Transaction New York, NY",
            "ledger_entry": "debit",
            "transaction_id": 2
        }
    ],
    "user_id": 3
}
